apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yegkvqgbz-go 
  janus-idp.io/tekton: yegkvqgbz-go
  backstage.io/kubernetes-id: yegkvqgbz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yegkvqgbz-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  